language: java

jdk: openjdk18
sudo: false

services:
  - postgresql
before_install:
  - psql -c 'create database job4j' -U user

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - cokes03@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always